### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Xtremeflux** [peterr-s/kill-adobe#1]
Hello Peter,

thanks for providing your files for this issue! This might be a stupid question from a complete newbie, but how does one install/run the files/code you have created? Does one need to install additional software to run the files? Any help would be greatly appreciated.

Best

**Comment by peterr-s** [comment]
The repository is a Visual Studio C++ project, so the easiest way to compile would be by importing it into Visual Studio. If you don't want to install VS, you could easily import it into any C IDE or run it through any C compiler you wish since there is only one source file and it is written in C, not C++. The only thing to note in that case is that you may need to manually link the Windows libraries required. This is fairly straightforward in VS, and is already configured in the project files if you choose to stick with that.

However, do note that I haven't maintained this code in a long time and Adobe may have changed some things. It was mostly a background process that I quickly made for my own use back when I used their photo editing software a lot.

Best of luck!

**Comment by 1024mb** [comment]
> 
> 
> The repository is a Visual Studio C++ project, so the easiest way to compile would be by importing it into Visual Studio. If you don't want to install VS, you could easily import it into any C IDE or run it through any C compiler you wish since there is only one source file and it is written in C, not C++. The only thing to note in that case is that you may need to manually link the Windows libraries required. This is fairly straightforward in VS, and is already configured in the project files if you choose to stick with that.
> 
> However, do note that I haven't maintained this code in a long time and Adobe may have changed some things. It was mostly a background process that I quickly made for my own use back when I used their photo editing software a lot.
> 
> Best of luck!

Can you please release a build?
